### ISSUE TITLE
加油吧

### ISSUE THREAD

**Issue by TUSITU123** [SteveUbuntu0/parahiko#1]

**Comment by SteveUbuntu0** [comment]
发病了？

From: ***@***.***>
Sent: 2022年10月21日 19:59
To: ***@***.***>
Cc: ***@***.***>
Subject: [SteveUbuntu0/parahiko] 哟，要写启动器了？ (Issue #1)


祝您写启动器一路有阻，bug多多

―

**Comment by SteveUbuntu0** [comment]
发病了？

**Comment by SteveUbuntu0** [comment]
你他妈发病就直说

**Comment by SteveUbuntu0** [comment]
顺便拜访一下你妈是否还活着

**Comment by SteveUbuntu0** [comment]
顺便给你挂这让你展示展示，等项目火了让你也丢丢人，看看一个人是多么没素质到别人项目的issue下提一些傻逼内容，我不说你，自己掂量啊常廷毅，我让你看看什么叫丢人

**Comment by SteveUbuntu0** [comment]
你改什么啊 怎么怕了？

你别忘了老子还有原文呢，哈哈

**Comment by TUSITU123** [comment]
对不起
